// Auto-generated by Codabra — do not edit manually
import React from 'react';

export default function LoginPage(): React.JSX.Element {
  return (
  <form>
    <h1>Sign in to your account</h1>
    <input type="email" id="email" name="email" placeholder="Email address" />
    <input type="password" id="password" name="password" placeholder="Password" />
    <button type="submit">Sign in</button>
  </form>
  );
}
