// Auto-generated by Codabra — do not edit manually
import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';

export const articles = sqliteTable('articles', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  title: text('title').notNull(),
  body: text('body'),
  published: integer('published').default(0).notNull(),
  createdAt: integer('createdAt').$defaultFn(() => Date.now()).notNull(),
});
export const users = sqliteTable('users', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  email: text('email').notNull(),
  name: text('name').notNull(),
  createdAt: integer('createdAt').$defaultFn(() => Date.now()).notNull(),
});
