import { execSync } from "child_process";
import * as path from "path";
import type { Provider } from "../../types";
import type { ConfigSet, CompilerResult } from "@codabra/core";
import { Compiler } from "@codabra/core";

/**
 * Next.js provider — v16 (App Router, Next.js 16.2.3).
 *
 * Responsibilities:
 *  - initCommand: bootstraps a new Next.js project
 *  - generate: uses @codabra/core Compiler to emit types, API routes, pages
 *  - startDev / runBuild: delegate to `next dev` / `next build`
 */
export class NextjsProviderV16 implements Provider {
    readonly name = "nextjs";
    readonly label = "Next.js 16 (App Router)";
    readonly initCommand =
        'npx create-next-app@16.2.3 . --typescript --eslint --tailwind --app --src-dir --import-alias "@/*" --yes';

    async generate(
        config: ConfigSet,
        appDir: string,
        options?: { orm?: string; database?: string },
    ): Promise<CompilerResult> {
        const compiler = new Compiler({
            appDir,
            strict: false,
            orm: options?.orm ?? "drizzle",
            database: options?.database ?? "sqlite",
        });
        return compiler.compile(config);
    }

    async startDev(appDir: string): Promise<void> {
        // Run next dev in the app directory — inherits stdio so output is visible
        const cmd = `cd ${JSON.stringify(appDir)} && npx next dev`;
        execSync(cmd, { stdio: "inherit" });
    }

    async runBuild(appDir: string): Promise<void> {
        execSync(`npx next build`, { cwd: appDir, stdio: "inherit" });
    }

    generateDockerfile(): string {
        // Build context is the monorepo root; app lives at apps/nextjs/
        return [
            `# Auto-generated by Codabra — do not edit manually`,
            `FROM node:20-alpine AS base`,
            `RUN npm install -g pnpm@9`,
            ``,
            `FROM base AS deps`,
            `WORKDIR /app`,
            `COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./`,
            `RUN pnpm install --frozen-lockfile`,
            ``,
            `FROM base AS builder`,
            `WORKDIR /app`,
            `COPY --from=deps /app/node_modules ./node_modules`,
            `COPY . .`,
            `ARG DATABASE_URL`,
            `ENV DATABASE_URL=$DATABASE_URL`,
            `ENV NODE_ENV=production`,
            `RUN pnpm generate && pnpm --filter nextjs build`,
            ``,
            `FROM base AS runner`,
            `WORKDIR /app`,
            `ENV NODE_ENV=production`,
            `COPY --from=builder /app/apps/nextjs/.next ./apps/nextjs/.next`,
            `COPY --from=builder /app/apps/nextjs/public ./apps/nextjs/public`,
            `COPY --from=builder /app/apps/nextjs/package.json ./apps/nextjs/package.json`,
            `COPY --from=builder /app/node_modules ./node_modules`,
            `COPY --from=builder /app/package.json ./`,
            `EXPOSE 3000`,
            `CMD ["pnpm", "--filter", "nextjs", "start"]`,
            ``,
        ].join("\n");
    }
}

/** Versioned map — key is the Next.js major version targeted */
export const nextjsVersions: Record<string, () => NextjsProviderV16> = {
    v16: () => new NextjsProviderV16(),
};

/** Default version */
export function createNextjsProvider(version = "v16"): NextjsProviderV16 {
    const factory = nextjsVersions[version];
    if (!factory) {
        throw new Error(
            `Unknown Next.js provider version: "${version}". Available: ${Object.keys(nextjsVersions).join(", ")}`,
        );
    }
    return factory();
}
