import type { OrmAdapter } from "../index";
import type { ModelDefinition, FieldShorthand } from "../../types";
import { normaliseField } from "../../validator/ModelValidator";

// ─────────────────────────────────────────────
// Dialect config interface
// ─────────────────────────────────────────────

interface DrizzleTypeEntry {
    fn: string;
    import: string;
    /** Extra arguments after the column name, e.g. "{ length: 255 }" for MySQL varchar */
    extraArgs?: string;
}

interface DrizzleDialectConfig {
    readonly tableFactory: string;
    readonly corePackage: string;
    /** Type map for simple field types (string, number, boolean, date) */
    readonly typeMap: Record<string, DrizzleTypeEntry>;
    /** Import name used for UUID and FK columns */
    readonly uuidImport: string;
    /** Import name used for date_now columns */
    readonly dateNowImport: string;
    /** FK column expression (no default value) */
    fkExpr(colName: string): string;
    /** Primary key id expression (with primaryKey + auto-generated default) */
    idPkExpr(colName: string): string;
    /** UUID field expression (with auto-generated default) */
    uuidExpr(colName: string): string;
    /** date_now field expression (with auto-set default) */
    dateNowExpr(colName: string): string;
    /** Content of the generated ORM client file */
    generateClientFile(): string;
    getDependencies(): Record<string, string>;
    getDevDependencies(): Record<string, string>;
}

// ─────────────────────────────────────────────
// SQLite dialect
// ─────────────────────────────────────────────

const sqliteDialect: DrizzleDialectConfig = {
    tableFactory: "sqliteTable",
    corePackage: "drizzle-orm/sqlite-core",
    typeMap: {
        string: { fn: "text", import: "text" },
        number: { fn: "integer", import: "integer" },
        boolean: { fn: "integer", import: "integer" }, // SQLite has no boolean — stored as 0/1
        date: { fn: "integer", import: "integer" }, // stored as epoch ms
    },
    uuidImport: "text",
    dateNowImport: "integer",
    fkExpr: (col) => `text('${col}')`,
    idPkExpr: (col) => `text('${col}').primaryKey().$defaultFn(() => crypto.randomUUID())`,
    uuidExpr: (col) => `text('${col}').$defaultFn(() => crypto.randomUUID())`,
    dateNowExpr: (col) => `integer('${col}').$defaultFn(() => Date.now())`,
    generateClientFile: () =>
        [
            `// Auto-generated by Codabra — do not edit manually`,
            `import Database from 'better-sqlite3';`,
            `import { drizzle } from 'drizzle-orm/better-sqlite3';`,
            `import * as schema from '@/drizzle/schema';`,
            ``,
            `const sqlite = new Database('sqlite.db');`,
            `export const db = drizzle(sqlite, { schema });`,
            ``,
        ].join("\n"),
    getDependencies: () => ({ "drizzle-orm": "^0.30.0", "better-sqlite3": "^9.0.0" }),
    getDevDependencies: () => ({ "drizzle-kit": "^0.21.0", "@types/better-sqlite3": "^7.6.0" }),
};

// ─────────────────────────────────────────────
// PostgreSQL dialect
// ─────────────────────────────────────────────

const postgresqlDialect: DrizzleDialectConfig = {
    tableFactory: "pgTable",
    corePackage: "drizzle-orm/pg-core",
    typeMap: {
        string: { fn: "text", import: "text" },
        number: { fn: "integer", import: "integer" },
        boolean: { fn: "boolean", import: "boolean" },
        date: { fn: "timestamp", import: "timestamp" },
    },
    uuidImport: "uuid",
    dateNowImport: "timestamp",
    fkExpr: (col) => `uuid('${col}')`,
    idPkExpr: (col) => `uuid('${col}').primaryKey().defaultRandom()`,
    uuidExpr: (col) => `uuid('${col}').defaultRandom()`,
    dateNowExpr: (col) => `timestamp('${col}').defaultNow()`,
    generateClientFile: () =>
        [
            `// Auto-generated by Codabra — do not edit manually`,
            `import { Pool } from 'pg';`,
            `import { drizzle } from 'drizzle-orm/node-postgres';`,
            `import * as schema from '@/drizzle/schema';`,
            ``,
            `const pool = new Pool({ connectionString: process.env.DATABASE_URL });`,
            `export const db = drizzle(pool, { schema });`,
            ``,
        ].join("\n"),
    getDependencies: () => ({ "drizzle-orm": "^0.30.0", pg: "^8.11.0" }),
    getDevDependencies: () => ({ "drizzle-kit": "^0.21.0", "@types/pg": "^8.11.0" }),
};

// ─────────────────────────────────────────────
// MySQL dialect
// ─────────────────────────────────────────────

const mysqlDialect: DrizzleDialectConfig = {
    tableFactory: "mysqlTable",
    corePackage: "drizzle-orm/mysql-core",
    typeMap: {
        string: { fn: "varchar", import: "varchar", extraArgs: "{ length: 255 }" },
        number: { fn: "int", import: "int" },
        boolean: { fn: "boolean", import: "boolean" },
        date: { fn: "timestamp", import: "timestamp" },
    },
    uuidImport: "varchar",
    dateNowImport: "timestamp",
    fkExpr: (col) => `varchar('${col}', { length: 36 })`,
    idPkExpr: (col) => `varchar('${col}', { length: 36 }).primaryKey().$defaultFn(() => crypto.randomUUID())`,
    uuidExpr: (col) => `varchar('${col}', { length: 36 }).$defaultFn(() => crypto.randomUUID())`,
    dateNowExpr: (col) => `timestamp('${col}').$defaultFn(() => new Date())`,
    generateClientFile: () =>
        [
            `// Auto-generated by Codabra — do not edit manually`,
            `import { createPool } from 'mysql2/promise';`,
            `import { drizzle } from 'drizzle-orm/mysql2';`,
            `import * as schema from '@/drizzle/schema';`,
            ``,
            `const pool = createPool({ uri: process.env.DATABASE_URL });`,
            `export const db = drizzle(pool, { schema, mode: 'default' });`,
            ``,
        ].join("\n"),
    getDependencies: () => ({ "drizzle-orm": "^0.30.0", mysql2: "^3.6.0" }),
    getDevDependencies: () => ({ "drizzle-kit": "^0.21.0" }),
};

const DIALECTS: Record<string, DrizzleDialectConfig> = {
    sqlite: sqliteDialect,
    postgresql: postgresqlDialect,
    mysql: mysqlDialect,
};

// ─────────────────────────────────────────────
// Schema generation
// ─────────────────────────────────────────────

function toTableName(modelName: string): string {
    return modelName.charAt(0).toLowerCase() + modelName.slice(1) + "s";
}

function generateDrizzleSchemaFile(models: ModelDefinition[], dialect: DrizzleDialectConfig): string {
    const importSet = new Set<string>([dialect.tableFactory]);
    const tableBlocks: string[] = [];

    for (const model of models) {
        const tableName = toTableName(model.name);
        const lines: string[] = [`export const ${tableName} = ${dialect.tableFactory}('${tableName}', {`];

        lines.push(`  id: ${dialect.idPkExpr("id")},`);

        for (const [name, rawField] of Object.entries(model.fields)) {
            const field = normaliseField(rawField as FieldShorthand);

            // Relation → FK column (same type as PK/UUID)
            if (field.relation) {
                const fkColName = `${name}Id`;
                importSet.add(dialect.uuidImport);
                lines.push(`  ${fkColName}: ${dialect.fkExpr(fkColName)},`);
                continue;
            }

            // UUID field
            if (field.type === "uuid") {
                importSet.add(dialect.uuidImport);
                lines.push(`  ${name}: ${dialect.uuidExpr(name)},`);
                continue;
            }

            // Auto-timestamped field
            if (field.type === "date_now") {
                importSet.add(dialect.dateNowImport);
                lines.push(`  ${name}: ${dialect.dateNowExpr(name)},`);
                continue;
            }

            // Simple typed field
            const typeInfo = dialect.typeMap[field.type];
            if (!typeInfo) continue;
            importSet.add(typeInfo.import);

            const optional = field.required === false;
            const baseCall = typeInfo.extraArgs
                ? `${typeInfo.fn}('${name}', ${typeInfo.extraArgs})`
                : `${typeInfo.fn}('${name}')`;

            let colExpr = baseCall;

            if (field.default !== undefined) {
                let defaultVal: string;
                // SQLite stores boolean as integer — use 1/0; other dialects use native bool literal
                if (field.type === "boolean" && dialect.typeMap.boolean?.fn === "integer") {
                    defaultVal = field.default ? "1" : "0";
                } else if (typeof field.default === "string") {
                    defaultVal = `'${field.default}'`;
                } else {
                    defaultVal = String(field.default);
                }
                colExpr += `.default(${defaultVal})`;
            }

            if (field.unique) colExpr += ".unique()";
            if (!optional) colExpr += ".notNull()";

            lines.push(`  ${name}: ${colExpr},`);
        }

        lines.push(`});`);
        tableBlocks.push(lines.join("\n"));
    }

    const importLine = `import { ${[...importSet].join(", ")} } from '${dialect.corePackage}';`;
    return [`// Auto-generated by Codabra — do not edit manually`, importLine, ``, ...tableBlocks, ``].join("\n");
}

// ─────────────────────────────────────────────
// DrizzleAdapter
// ─────────────────────────────────────────────

function drizzleTable(modelName: string): string {
    return toTableName(modelName);
}

export class DrizzleAdapter implements OrmAdapter {
    readonly name = "drizzle";
    readonly label = "Drizzle ORM";

    private readonly dialect: DrizzleDialectConfig;
    private readonly database: string;

    constructor(database: string) {
        const dialect = DIALECTS[database];
        if (!dialect) {
            throw new Error(
                `Drizzle ORM does not support database "${database}". Supported: ${Object.keys(DIALECTS).join(", ")}`,
            );
        }
        this.dialect = dialect;
        this.database = database;
    }

    getSchemaFilePath(): string {
        return "src/drizzle/schema.ts";
    }
    getClientFilePath(): string {
        return "src/lib/db.ts";
    }

    generateSchemaFile(models: ModelDefinition[]): string {
        return generateDrizzleSchemaFile(models, this.dialect);
    }

    generateClientFile(): string {
        return this.dialect.generateClientFile();
    }

    getRouteImports(modelName: string): string[] {
        const table = drizzleTable(modelName);
        return [
            `import { db } from '@/lib/db';`,
            `import { ${table} } from '@/drizzle/schema';`,
            `import { eq } from 'drizzle-orm';`,
        ];
    }

    getFunctionImports(): string[] {
        return [
            `import { db } from '@/lib/db';`,
            `import * as schema from '@/drizzle/schema';`,
            `import { eq } from 'drizzle-orm';`,
        ];
    }

    routeFindMany(modelName: string): string {
        return `await db.select().from(${drizzleTable(modelName)})`;
    }

    routeFindUnique(modelName: string): string {
        const table = drizzleTable(modelName);
        return `await db.select().from(${table}).where(eq(${table}.id, id)).then((r) => r[0] ?? null)`;
    }

    routeCreate(modelName: string, dataExpr: string): string {
        const table = drizzleTable(modelName);
        if (this.database === "mysql") {
            // MySQL does not support RETURNING — insert then re-select
            return (
                `await db.insert(${table}).values(${dataExpr}).$returningId()` +
                `.then(([r]) => db.select().from(${table}).where(eq(${table}.id, r.id)).then((rows) => rows[0]))`
            );
        }
        return `await db.insert(${table}).values(${dataExpr}).returning().then((r) => r[0])`;
    }

    routeUpdate(modelName: string, _whereExpr: string, dataExpr: string): string {
        const table = drizzleTable(modelName);
        if (this.database === "mysql") {
            // MySQL does not support RETURNING — update then re-select
            return (
                `await db.update(${table}).set(${dataExpr}).where(eq(${table}.id, id))` +
                `.then(() => db.select().from(${table}).where(eq(${table}.id, id)).then((rows) => rows[0]))`
            );
        }
        return `await db.update(${table}).set(${dataExpr}).where(eq(${table}.id, id)).returning().then((r) => r[0])`;
    }

    routeDelete(modelName: string, _whereExpr: string): string {
        return `await db.delete(${drizzleTable(modelName)}).where(eq(${drizzleTable(modelName)}.id, id))`;
    }

    routeLoadResource(modelName: string): string {
        const table = drizzleTable(modelName);
        return `await db.select().from(${table}).where(eq(${table}.id, id)).then((r) => r[0] ?? null)`;
    }

    getCreateBodyTypecast(_modelName: string): string {
        return `body as Record<string, unknown>`;
    }
    getUpdateBodyTypecast(_modelName: string): string {
        return `body as Record<string, unknown>`;
    }

    fnCreate(modelName: string, dataExpr: string): string {
        const table = drizzleTable(modelName);
        if (this.database === "mysql") {
            return (
                `await db.insert(schema.${table}).values(${dataExpr}).$returningId()` +
                `.then(([r]) => db.select().from(schema.${table}).where(eq(schema.${table}.id, r.id)).then((rows) => rows[0]))`
            );
        }
        return `await db.insert(schema.${table}).values(${dataExpr}).returning().then((r) => r[0])`;
    }

    fnUpdate(modelName: string, whereExpr: string, dataExpr: string): string {
        const table = drizzleTable(modelName);
        if (this.database === "mysql") {
            return (
                `await db.update(schema.${table}).set(${dataExpr}).where(eq(schema.${table}.id, ${whereExpr}.id))` +
                `.then(() => db.select().from(schema.${table}).where(eq(schema.${table}.id, ${whereExpr}.id)).then((rows) => rows[0]))`
            );
        }
        return `await db.update(schema.${table}).set(${dataExpr}).where(eq(schema.${table}.id, ${whereExpr}.id)).returning().then((r) => r[0])`;
    }

    fnDelete(modelName: string, whereExpr: string): string {
        const table = drizzleTable(modelName);
        return `await db.delete(schema.${table}).where(eq(schema.${table}.id, ${whereExpr}.id))`;
    }

    fnFindMany(modelName: string, whereExpr?: string): string {
        const table = drizzleTable(modelName);
        if (whereExpr) return `await db.select().from(schema.${table}) /* filter: ${whereExpr} */`;
        return `await db.select().from(schema.${table})`;
    }

    getDependencies(): Record<string, string> {
        return this.dialect.getDependencies();
    }

    getDevDependencies(): Record<string, string> {
        return this.dialect.getDevDependencies();
    }
}
