import type { OrmAdapter } from "../index";
import type { ModelDefinition, FieldShorthand, ModelField } from "../../types";
import { normaliseField, isPrimitive } from "../../validator/ModelValidator";

// ─────────────────────────────────────────────
// Drizzle type maps (SQLite)
// ─────────────────────────────────────────────

const DRIZZLE_SQLITE_TYPE_MAP: Record<string, { fn: string; import: string }> = {
    string: { fn: "text", import: "text" },
    number: { fn: "integer", import: "integer" },
    boolean: { fn: "integer", import: "integer" }, // SQLite has no boolean; store as 0/1
    date: { fn: "integer", import: "integer" }, // epoch ms
    date_now: { fn: "integer", import: "integer" }, // epoch ms with $defaultFn
    uuid: { fn: "text", import: "text" },
};

// ─────────────────────────────────────────────
// Schema generation helpers
// ─────────────────────────────────────────────

/** "User" → "users", "ArticleTag" → "articleTags" */
function toTableName(modelName: string): string {
    const camel = modelName.charAt(0).toLowerCase() + modelName.slice(1);
    return camel + "s";
}

function generateDrizzleSchemaFile(models: ModelDefinition[]): string {
    const importSet = new Set<string>(["sqliteTable"]);
    const tableBlocks: string[] = [];

    for (const model of models) {
        const tableName = toTableName(model.name);
        const varName = tableName; // e.g. "users"
        const lines: string[] = [`export const ${varName} = sqliteTable('${tableName}', {`];
        lines.push(`  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),`);

        for (const [name, rawField] of Object.entries(model.fields)) {
            const field = normaliseField(rawField as FieldShorthand);

            if (field.relation) {
                // FK reference — handled as a text column after own fields
                const fkColName = `${name}Id`;
                importSet.add("text");
                lines.push(`  ${fkColName}: text('${fkColName}'),`);
                continue;
            }

            const typeInfo = DRIZZLE_SQLITE_TYPE_MAP[field.type];
            if (!typeInfo) continue; // unknown / relation ref — skip
            importSet.add(typeInfo.import);

            const optional = field.required === false;
            let colExpr = `${typeInfo.fn}('${name}')`;

            if (field.type === "uuid") {
                colExpr += `.$defaultFn(() => crypto.randomUUID())`;
            } else if (field.type === "date_now") {
                colExpr += `.$defaultFn(() => Date.now())`;
            } else if (field.default !== undefined) {
                let defaultVal: string;
                if (field.type === "boolean") {
                    // SQLite stores booleans as integers: false → 0, true → 1
                    defaultVal = field.default ? "1" : "0";
                } else if (typeof field.default === "string") {
                    defaultVal = `'${field.default}'`;
                } else {
                    defaultVal = String(field.default);
                }
                colExpr += `.default(${defaultVal})`;
            }

            if (field.unique) colExpr += ".unique()";
            if (!optional) colExpr += ".notNull()";

            lines.push(`  ${name}: ${colExpr},`);
        }

        lines.push(`});`);
        tableBlocks.push(lines.join("\n"));
    }

    const importLine = `import { ${[...importSet].join(", ")} } from 'drizzle-orm/sqlite-core';`;

    return [`// Auto-generated by Codabra — do not edit manually`, importLine, ``, ...tableBlocks, ``].join("\n");
}

// ─────────────────────────────────────────────
// Drizzle accessor helpers
// ─────────────────────────────────────────────

/** "User" → "users" (the exported table var name in schema.ts) */
function drizzleTable(modelName: string): string {
    return toTableName(modelName);
}

// ─────────────────────────────────────────────
// DrizzleAdapter
// ─────────────────────────────────────────────

export class DrizzleAdapter implements OrmAdapter {
    readonly name = "drizzle";
    readonly label = "Drizzle ORM (SQLite)";

    getSchemaFilePath(): string {
        // Lives inside src/ so the @/* alias and relative imports from src/lib/ both work.
        return "src/drizzle/schema.ts";
    }

    getClientFilePath(): string {
        return "src/lib/db.ts";
    }

    generateSchemaFile(models: ModelDefinition[]): string {
        return generateDrizzleSchemaFile(models);
    }

    generateClientFile(): string {
        return [
            `// Auto-generated by Codabra — do not edit manually`,
            `import Database from 'better-sqlite3';`,
            `import { drizzle } from 'drizzle-orm/better-sqlite3';`,
            `import * as schema from '@/drizzle/schema';`,
            ``,
            `const sqlite = new Database('sqlite.db');`,
            `export const db = drizzle(sqlite, { schema });`,
            ``,
        ].join("\n");
    }

    getRouteImports(modelName: string): string[] {
        const table = drizzleTable(modelName);
        return [
            `import { db } from '@/lib/db';`,
            `import { ${table} } from '@/drizzle/schema';`,
            `import { eq } from 'drizzle-orm';`,
        ];
    }

    getFunctionImports(): string[] {
        return [
            `import { db } from '@/lib/db';`,
            `import * as schema from '@/drizzle/schema';`,
            `import { eq } from 'drizzle-orm';`,
        ];
    }

    routeFindMany(modelName: string): string {
        const table = drizzleTable(modelName);
        return `await db.select().from(${table})`;
    }

    routeFindUnique(modelName: string): string {
        const table = drizzleTable(modelName);
        return `await db.select().from(${table}).where(eq(${table}.id, id)).then((r) => r[0] ?? null)`;
    }

    routeCreate(modelName: string, dataExpr: string): string {
        const table = drizzleTable(modelName);
        return `await db.insert(${table}).values(${dataExpr}).returning().then((r) => r[0])`;
    }

    routeUpdate(modelName: string, _whereExpr: string, dataExpr: string): string {
        const table = drizzleTable(modelName);
        // whereExpr from RouteParser is "{ id }" — for Drizzle we always use eq by id
        return `await db.update(${table}).set(${dataExpr}).where(eq(${table}.id, id)).returning().then((r) => r[0])`;
    }

    routeDelete(modelName: string, _whereExpr: string): string {
        const table = drizzleTable(modelName);
        return `await db.delete(${table}).where(eq(${table}.id, id))`;
    }

    routeLoadResource(modelName: string): string {
        const table = drizzleTable(modelName);
        return `await db.select().from(${table}).where(eq(${table}.id, id)).then((r) => r[0] ?? null)`;
    }

    getCreateBodyTypecast(_modelName: string): string {
        return `body as Record<string, unknown>`;
    }

    getUpdateBodyTypecast(_modelName: string): string {
        return `body as Record<string, unknown>`;
    }

    fnCreate(modelName: string, dataExpr: string): string {
        const table = drizzleTable(modelName);
        return `await db.insert(schema.${table}).values(${dataExpr}).returning().then((r) => r[0])`;
    }

    fnUpdate(modelName: string, whereExpr: string, dataExpr: string): string {
        const table = drizzleTable(modelName);
        // whereExpr is an object literal like "{ id: params.id }" — extract first key for eq()
        // For simplicity, assume where has an "id" key
        return `await db.update(schema.${table}).set(${dataExpr}).where(eq(schema.${table}.id, ${whereExpr}.id)).returning().then((r) => r[0])`;
    }

    fnDelete(modelName: string, whereExpr: string): string {
        const table = drizzleTable(modelName);
        return `await db.delete(schema.${table}).where(eq(schema.${table}.id, ${whereExpr}.id))`;
    }

    fnFindMany(modelName: string, whereExpr?: string): string {
        const table = drizzleTable(modelName);
        if (whereExpr) {
            // whereExpr is an object literal — generate a select with a note
            return `await db.select().from(schema.${table}) /* filter: ${whereExpr} */`;
        }
        return `await db.select().from(schema.${table})`;
    }

    getDependencies(): Record<string, string> {
        return {
            "drizzle-orm": "^0.30.0",
            "better-sqlite3": "^9.0.0",
        };
    }

    getDevDependencies(): Record<string, string> {
        return {
            "drizzle-kit": "^0.21.0",
            "@types/better-sqlite3": "^7.6.0",
        };
    }
}
