import * as fs from "fs";
import * as path from "path";
import { getProvider } from "@codabra/providers";
import type { ProviderConfig } from "./commands/generate";

// ─────────────────────────────────────────────
// File helpers
// ─────────────────────────────────────────────

function writeFile(filePath: string, content: string): void {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content, "utf-8");
}

// ─────────────────────────────────────────────
// Per-database service blocks
// ─────────────────────────────────────────────

function postgresDevService(projectName: string): string {
    return [
        `  postgres:`,
        `    image: postgres:16-alpine`,
        `    restart: unless-stopped`,
        `    environment:`,
        `      POSTGRES_DB: ${projectName}_dev`,
        `      POSTGRES_USER: postgres`,
        `      POSTGRES_PASSWORD: postgres`,
        `    ports:`,
        `      - "5432:5432"`,
        `    volumes:`,
        `      - postgres_dev_data:/var/lib/postgresql/data`,
    ].join("\n");
}

function postgresProdService(projectName: string): string {
    return [
        `  postgres:`,
        `    image: postgres:16-alpine`,
        `    restart: unless-stopped`,
        `    environment:`,
        `      POSTGRES_DB: \${POSTGRES_DB:-${projectName}_prod}`,
        `      POSTGRES_USER: \${POSTGRES_USER:-postgres}`,
        `      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}`,
        `    volumes:`,
        `      - postgres_prod_data:/var/lib/postgresql/data`,
    ].join("\n");
}

function mysqlDevService(projectName: string): string {
    return [
        `  mysql:`,
        `    image: mysql:8.0`,
        `    restart: unless-stopped`,
        `    environment:`,
        `      MYSQL_DATABASE: ${projectName}_dev`,
        `      MYSQL_ROOT_PASSWORD: root`,
        `    ports:`,
        `      - "3306:3306"`,
        `    volumes:`,
        `      - mysql_dev_data:/var/lib/mysql`,
    ].join("\n");
}

function mysqlProdService(projectName: string): string {
    return [
        `  mysql:`,
        `    image: mysql:8.0`,
        `    restart: unless-stopped`,
        `    environment:`,
        `      MYSQL_DATABASE: \${MYSQL_DATABASE:-${projectName}_prod}`,
        `      MYSQL_ROOT_PASSWORD: \${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD is required}`,
        `    volumes:`,
        `      - mysql_prod_data:/var/lib/mysql`,
    ].join("\n");
}

/** App service block in prod compose — references the provider-specific Dockerfile */
function appProdService(providerName: string, databases: string[]): string {
    const dependsOn = databases.filter((db) => db === "postgresql" || db === "mysql");

    const lines = [
        `  ${providerName}:`,
        `    build:`,
        `      context: ..`,
        `      dockerfile: docker/${providerName}/Dockerfile`,
        `    restart: unless-stopped`,
        `    ports:`,
        `      - "\${PORT:-3000}:3000"`,
        `    environment:`,
        `      NODE_ENV: production`,
        `      DATABASE_URL: \${DATABASE_URL:?DATABASE_URL is required}`,
    ];

    if (dependsOn.length > 0) {
        lines.push(`    depends_on:`);
        for (const db of dependsOn) {
            lines.push(`      - ${db === "postgresql" ? "postgres" : "mysql"}`);
        }
    }

    return lines.join("\n");
}

// ─────────────────────────────────────────────
// Volume declarations
// ─────────────────────────────────────────────

function devVolumes(databases: string[]): string {
    const volumes: string[] = [];
    if (databases.includes("postgresql")) volumes.push("  postgres_dev_data:");
    if (databases.includes("mysql")) volumes.push("  mysql_dev_data:");
    return volumes.length > 0 ? `\nvolumes:\n${volumes.join("\n")}\n` : "";
}

function prodVolumes(databases: string[]): string {
    const volumes: string[] = [];
    if (databases.includes("postgresql")) volumes.push("  postgres_prod_data:");
    if (databases.includes("mysql")) volumes.push("  mysql_prod_data:");
    return volumes.length > 0 ? `\nvolumes:\n${volumes.join("\n")}\n` : "";
}

// ─────────────────────────────────────────────
// Compose file generators
// ─────────────────────────────────────────────

function generateDevCompose(projectName: string, databases: string[]): string {
    const serverDbs = databases.filter((db) => db !== "sqlite");
    const lines = [
        `# Auto-generated by Codabra — do not edit manually`,
        `# Dev: database services only (app runs locally for hot-reload)`,
        ``,
    ];

    if (serverDbs.length === 0) {
        lines.push(`# SQLite requires no Docker service — the database is a local file.`);
        lines.push(`# This file is intentionally empty for SQLite-only projects.`);
        lines.push(`services: {}`);
        return lines.join("\n") + "\n";
    }

    lines.push(`services:`);
    for (const db of serverDbs) {
        if (db === "postgresql") lines.push(postgresDevService(projectName));
        if (db === "mysql") lines.push(mysqlDevService(projectName));
        lines.push(``);
    }

    return lines.join("\n") + devVolumes(serverDbs);
}

function generateProdCompose(projectName: string, providerConfigs: ProviderConfig[]): string {
    const databases = [...new Set(providerConfigs.map((c) => c.database))];
    const serverDbs = databases.filter((db) => db !== "sqlite");
    const providerNames = [...new Set(providerConfigs.map((c) => c.provider))];

    const lines = [
        `# Auto-generated by Codabra — do not edit manually`,
        `# Prod: full stack — set DATABASE_URL and DB passwords via environment or .env`,
        ``,
        `services:`,
    ];

    for (const db of serverDbs) {
        if (db === "postgresql") lines.push(postgresProdService(projectName));
        if (db === "mysql") lines.push(mysqlProdService(projectName));
        lines.push(``);
    }

    for (const providerName of providerNames) {
        lines.push(appProdService(providerName, databases));
        lines.push(``);
    }

    return lines.join("\n") + prodVolumes(serverDbs);
}

function generateMakefile(): string {
    const tab = "\t";
    return [
        `.PHONY: dev-up dev-down dev-restart dev-build prod-up prod-down prod-restart prod-build`,
        ``,
        `dev-up:`,
        `${tab}docker compose -f docker/docker-compose.dev.yml up -d`,
        ``,
        `dev-down:`,
        `${tab}docker compose -f docker/docker-compose.dev.yml down`,
        ``,
        `dev-restart:`,
        `${tab}docker compose -f docker/docker-compose.dev.yml restart`,
        ``,
        `dev-build:`,
        `${tab}docker compose -f docker/docker-compose.dev.yml build`,
        ``,
        `prod-up:`,
        `${tab}docker compose -f docker/docker-compose.prod.yml up -d`,
        ``,
        `prod-down:`,
        `${tab}docker compose -f docker/docker-compose.prod.yml down`,
        ``,
        `prod-restart:`,
        `${tab}docker compose -f docker/docker-compose.prod.yml restart`,
        ``,
        `prod-build:`,
        `${tab}docker compose -f docker/docker-compose.prod.yml build`,
        ``,
    ].join("\n");
}

// ─────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────

/**
 * Generates (or regenerates) all Docker config files:
 *   docker/<providerName>/Dockerfile   ← provider-specific, from provider.generateDockerfile()
 *   docker/docker-compose.dev.yml      ← DB services only (app runs locally)
 *   docker/docker-compose.prod.yml     ← full stack (app + DBs)
 *   Makefile                           ← dev-up/down/restart/build + prod-*
 *
 * Safe to call multiple times — always overwrites with the current provider config state.
 */
export function generateDockerConfig(
    projectDir: string,
    projectName: string,
    providerConfigs: ProviderConfig[],
): void {
    const databases = [...new Set(providerConfigs.map((c) => c.database))];
    const dockerDir = path.join(projectDir, "docker");

    // Per-provider Dockerfiles
    const uniqueProviders = [...new Set(providerConfigs.map((c) => c.provider))];
    for (const providerName of uniqueProviders) {
        try {
            const provider = getProvider(providerName).create();
            const dockerfileContent = provider.generateDockerfile();
            writeFile(path.join(dockerDir, providerName, "Dockerfile"), dockerfileContent);
        } catch {
            // Unknown provider — skip Dockerfile generation rather than crashing
        }
    }

    writeFile(path.join(dockerDir, "docker-compose.dev.yml"), generateDevCompose(projectName, databases));
    writeFile(path.join(dockerDir, "docker-compose.prod.yml"), generateProdCompose(projectName, providerConfigs));
    writeFile(path.join(projectDir, "Makefile"), generateMakefile());
}

/**
 * Returns true if the dev compose file in projectDir contains actual DB services
 * (i.e., any provider uses a non-SQLite database).
 */
export function hasDockerDevServices(projectDir: string): boolean {
    const composePath = path.join(projectDir, "docker", "docker-compose.dev.yml");
    if (!fs.existsSync(composePath)) return false;
    const content = fs.readFileSync(composePath, "utf-8");
    return content.includes("image:");
}

// ─────────────────────────────────────────────
// Docker installation check
// ─────────────────────────────────────────────

import { execSync } from "child_process";

/** Returns true if the `docker` binary is available on the system. */
export function isDockerInstalled(): boolean {
    try {
        execSync("docker --version", { stdio: "ignore" });
        return true;
    } catch {
        return false;
    }
}

/**
 * Detects the current OS platform for Docker installation guidance.
 * Returns "linux" | "macos" | "windows".
 */
export function detectPlatform(): "linux" | "macos" | "windows" {
    const p = process.platform;
    if (p === "darwin") return "macos";
    if (p === "win32") return "windows";
    return "linux";
}

/**
 * Attempts to install Docker on Linux using the official convenience script.
 * Throws on failure. Only call after user confirmation.
 */
export function installDockerLinux(): void {
    execSync("curl -fsSL https://get.docker.com | sh", { stdio: "inherit" });
}

const DOCKER_INSTALL_URL = "https://docs.docker.com/get-docker/";

/**
 * If the chosen database requires Docker (i.e. non-SQLite), checks whether
 * Docker is installed and offers to install it interactively.
 *
 * `confirm` must be passed in to avoid importing @inquirer/prompts here
 * (keeps this module framework-agnostic and easier to test).
 */
export async function ensureDockerIfNeeded(
    database: string,
    confirmFn: (opts: { message: string; default?: boolean }) => Promise<boolean>,
): Promise<void> {
    if (database === "sqlite") return; // SQLite is a local file — no Docker needed

    if (isDockerInstalled()) return; // Already installed — nothing to do

    const platform = detectPlatform();

    console.log("");
    console.log("  Docker is required to run the database service locally.");
    console.log(`  Install guide: ${DOCKER_INSTALL_URL}`);
    console.log("");

    if (platform === "linux") {
        const install = await confirmFn({
            message: "Docker is not installed. Install it now via the official script? (curl -fsSL https://get.docker.com | sh)",
            default: true,
        });
        if (install) {
            try {
                installDockerLinux();
            } catch {
                console.log("  Docker installation failed. Please install manually and re-run.");
            }
        } else {
            console.log(`  Skipping Docker install. Run 'make dev-up' after installing it from ${DOCKER_INSTALL_URL}`);
        }
    } else if (platform === "macos") {
        console.log("  On macOS, install Docker Desktop or run: brew install --cask docker");
        console.log(`  Then run 'make dev-up' to start your database.`);
    } else {
        console.log("  On Windows, download Docker Desktop from:");
        console.log(`  ${DOCKER_INSTALL_URL}`);
        console.log(`  Then run 'make dev-up' to start your database.`);
    }
    console.log("");
}
