// Auto-generated by Codabra — do not edit manually
import React from 'react';

export default function UserListPage(): React.JSX.Element {
  // TODO: replace with real data fetching
  const User: Record<string, unknown>[] = [];
  return (
  <div>
    <h1>Users</h1>
    {/* Render table of User */}
    <table>
      <tbody>
        {User.map((item, i) => (
          <tr key={String(item['id'] ?? i)}><td>{JSON.stringify(item)}</td></tr>
        ))}
      </tbody>
    </table>
  </div>
  );
}
