import type { ModelDefinition, FieldShorthand, ModelField, RelationDef } from "../types";
import { normaliseField, isPrimitive } from "../validator/ModelValidator";

// ─────────────────────────────────────────────
// TypeScript interface generation
// ─────────────────────────────────────────────

const PRISMA_TYPE_MAP: Record<string, string> = {
    string: "String",
    number: "Int",
    boolean: "Boolean",
    date: "DateTime",
    date_now: "DateTime",
    uuid: "String",
};

const TS_TYPE_MAP: Record<string, string> = {
    string: "string",
    number: "number",
    boolean: "boolean",
    date: "Date",
    date_now: "Date",
    uuid: "string",
};

function tsType(field: ModelField): string {
    if (isPrimitive(field.type)) {
        return TS_TYPE_MAP[field.type] ?? "unknown";
    }
    // Relation: reference another model type
    if (field.relation) {
        if (field.relation.type === "one-to-many" || field.relation.type === "many-to-many") {
            return `${field.type}[]`;
        }
        return field.type;
    }
    return field.type; // pass-through (handles direct model name shorthand)
}

/**
 * Generates a TypeScript interface for a model, including relation fields
 * and import statements for referenced model types.
 */
export function generateModelInterface(model: ModelDefinition): string {
    const imports: string[] = [];
    const fieldLines: string[] = [];

    for (const [name, rawField] of Object.entries(model.fields)) {
        const field = normaliseField(rawField as FieldShorthand);
        const optional = field.required === false ? "?" : "";

        if (field.relation) {
            const relType = tsType(field);
            fieldLines.push(`  ${name}${optional}: ${relType};`);
            // Add import for the related model type
            const importLine = `import type { ${field.type} } from './${field.type}';`;
            if (!imports.includes(importLine)) {
                imports.push(importLine);
            }
        } else {
            fieldLines.push(`  ${name}${optional}: ${tsType(field)};`);
        }
    }

    const lines: string[] = [
        `// Auto-generated by Codabra — do not edit manually`,
        ``,
        ...imports,
        ...(imports.length > 0 ? [``, `export interface ${model.name} {`] : [`export interface ${model.name} {`]),
        `  id: string;`,
        ...fieldLines,
        `}`,
        ``,
    ];

    return lines.join("\n");
}

// ─────────────────────────────────────────────
// Prisma schema generation
// ─────────────────────────────────────────────

function toPrismaDefault(rawType: string): string {
    if (rawType === "date_now") return " @default(now())";
    if (rawType === "uuid") return " @default(uuid())";
    return "";
}

function fieldAnnotations(field: ModelField): string {
    const parts: string[] = [];
    if (field.unique) parts.push("@unique");
    return parts.length ? ` ${parts.join(" ")}` : "";
}

// ─────────────────────────────────────────────
// Relation backref collection
// ─────────────────────────────────────────────

interface BackrefEntry {
    /** The model that declared this relation (source) */
    sourceModel: string;
    /** The field name in the source model */
    sourceField: string;
    /** The type of relation as declared on the source */
    relationType: RelationDef["type"];
    /** Unique relation name: <SourceModel>_<fieldName> */
    relationName: string;
}

/**
 * Pass 1: collect all relations declared across all models,
 * keyed by target model name.
 */
function collectBackrefs(models: ModelDefinition[]): Map<string, BackrefEntry[]> {
    const map = new Map<string, BackrefEntry[]>();

    for (const model of models) {
        for (const [fieldName, rawField] of Object.entries(model.fields)) {
            const field = normaliseField(rawField as FieldShorthand);
            if (!field.relation) continue;

            const target = field.relation.model;
            const entry: BackrefEntry = {
                sourceModel: model.name,
                sourceField: fieldName,
                relationType: field.relation.type,
                relationName: `${model.name}_${fieldName}`,
            };

            const existing = map.get(target) ?? [];
            existing.push(entry);
            map.set(target, existing);
        }
    }

    return map;
}

/**
 * Returns the set of field names already declared on a model (excluding backrefs).
 */
function declaredFieldNames(model: ModelDefinition): Set<string> {
    return new Set(Object.keys(model.fields));
}

/**
 * Generates a Prisma model block for a ModelDefinition.
 * Pass 2: also emits backref fields collected from other models' relations.
 */
export function generatePrismaModel(model: ModelDefinition, backrefs: Map<string, BackrefEntry[]> = new Map()): string {
    const lines: string[] = [`model ${model.name} {`, `  id  String  @id @default(uuid())`];
    const existingFields = declaredFieldNames(model);

    // Emit explicitly declared fields
    for (const [name, rawField] of Object.entries(model.fields)) {
        const field = normaliseField(rawField as FieldShorthand);

        if (field.relation) {
            const relType = field.relation.type;
            const target = field.type;
            const relName = `${model.name}_${name}`;

            if (relType === "many-to-many") {
                lines.push(`  ${name}  ${target}[]  @relation("${relName}")`);
            } else if (relType === "one-to-many") {
                // Source of one-to-many: holds the array
                lines.push(`  ${name}  ${target}[]`);
            } else {
                // one-to-one source: holds optional reference
                lines.push(`  ${name}  ${target}?`);
            }
            continue;
        }

        const prismaType = PRISMA_TYPE_MAP[field.type] ?? field.type;
        const optional = field.required === false ? "?" : "";
        const defaultVal = toPrismaDefault(field.type);
        const annotations = fieldAnnotations(field);

        lines.push(`  ${name}  ${prismaType}${optional}${defaultVal}${annotations}`);
    }

    // Emit backref fields for relations pointing TO this model
    const inboundRefs = backrefs.get(model.name) ?? [];
    for (const ref of inboundRefs) {
        // Deduplication: skip if the model already declares a field of this type
        const wouldConflict = [...existingFields].some((fn) => {
            const raw = model.fields[fn];
            if (!raw) return false;
            const f = normaliseField(raw as FieldShorthand);
            return f.type === ref.sourceModel;
        });
        if (wouldConflict) continue;

        // Derive a safe backref field name: lowercase source model name
        const backrefFieldName = ref.sourceModel.charAt(0).toLowerCase() + ref.sourceModel.slice(1);

        if (ref.relationType === "many-to-many") {
            lines.push(`  ${backrefFieldName}s  ${ref.sourceModel}[]  @relation("${ref.relationName}")`);
        } else if (ref.relationType === "one-to-many") {
            // This model is the "many" side — it needs a FK to the source
            const fkField = `${backrefFieldName}Id`;
            lines.push(
                `  ${backrefFieldName}  ${ref.sourceModel}  @relation("${ref.relationName}", fields: [${fkField}], references: [id])`,
            );
            lines.push(`  ${fkField}  String`);
        } else {
            // one-to-one: this model is the "owned" side — it needs a FK
            const fkField = `${backrefFieldName}Id`;
            lines.push(
                `  ${backrefFieldName}  ${ref.sourceModel}  @relation("${ref.relationName}", fields: [${fkField}], references: [id])`,
            );
            lines.push(`  ${fkField}  String  @unique`);
        }
    }

    lines.push(`}`);
    return lines.join("\n");
}

/**
 * Generates the complete Prisma schema file content,
 * with proper two-sided relation declarations.
 */
export function generatePrismaSchema(models: ModelDefinition[]): string {
    const header = [
        `// Auto-generated by Codabra — do not edit manually`,
        ``,
        `generator client {`,
        `  provider = "prisma-client-js"`,
        `}`,
        ``,
        `datasource db {`,
        `  provider = "sqlite"`,
        `  url      = env("DATABASE_URL")`,
        `}`,
        ``,
    ].join("\n");

    const backrefs = collectBackrefs(models);
    const modelBlocks = models.map((m) => generatePrismaModel(m, backrefs)).join("\n\n");
    return header + modelBlocks + "\n";
}
