import type { VoterDefinition, VoterRule, VoterCondition } from "../types";

// ─────────────────────────────────────────────
// Condition expression generation
// ─────────────────────────────────────────────

function generateConditionExpr(condition: VoterCondition | undefined): string {
    if (!condition) return "true";

    if (condition.self) {
        // Resource ownership: the authenticated user must own the resource
        return `resource != null && (resource as Record<string, unknown>)['userId'] === userId`;
    }

    if (condition.field && condition.operator !== undefined) {
        const lhs = `(resource as Record<string, unknown>)['${condition.field}']`;
        const rhs = JSON.stringify(condition.value);
        return `resource != null && ${lhs} ${condition.operator} ${rhs}`;
    }

    return "true";
}

// ─────────────────────────────────────────────
// Rule block generation
// ─────────────────────────────────────────────

function generateRuleBlock(rule: VoterRule, pad: string): string[] {
    const lines: string[] = [];
    const methodsExpr = JSON.stringify(rule.methods);
    const condExpr = generateConditionExpr(rule.condition);

    lines.push(`${pad}if (${methodsExpr}.includes(method as never)) {`);
    if (condExpr === "true") {
        lines.push(`${pad}  return true;`);
    } else {
        lines.push(`${pad}  return ${condExpr};`);
    }
    lines.push(`${pad}}`);
    return lines;
}

// ─────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────

/**
 * Generates the content of a voter check file.
 * Emitted to: src/lib/voters/<Name>.ts
 */
export function generateVoterFile(voter: VoterDefinition): string {
    const fnName = `check${voter.name}`;
    const lines: string[] = [
        `// Auto-generated by Codabra — do not edit manually`,
        `import { NextRequest } from 'next/server';`,
        ``,
        `/**`,
        ` * Checks whether the authenticated user is allowed to perform \`method\` on \`resource\`.`,
        ` * @param req       Incoming Next.js request`,
        ` * @param method    HTTP method (GET, POST, PUT, PATCH, DELETE)`,
        ` * @param resource  The target resource object (may be null for collection routes)`,
        ` * @param userId    Authenticated user ID, or null if unauthenticated`,
        ` */`,
        `export function ${fnName}(`,
        `    _req: NextRequest,`,
        `    method: string,`,
        `    resource: unknown,`,
        `    userId: string | null`,
        `): boolean {`,
    ];

    for (const rule of voter.rules) {
        lines.push(...generateRuleBlock(rule, "  "));
    }

    lines.push(`  return false;`);
    lines.push(`}`);
    lines.push(``);

    return lines.join("\n");
}

/**
 * Generates the content of the auth utility file.
 * Emitted to: src/lib/auth.ts
 */
export function generateAuthFile(): string {
    return [
        `// Auto-generated by Codabra — do not edit manually`,
        `import { NextRequest } from 'next/server';`,
        ``,
        `/**`,
        ` * Extracts the authenticated user ID from the request's Authorization header.`,
        ` * Expects a Bearer token in the format: "Authorization: Bearer <token>"`,
        ` * In production, replace this with proper JWT verification.`,
        ` * Returns null when the header is missing or malformed.`,
        ` */`,
        `export function getAuthUser(req: NextRequest): string | null {`,
        `    const auth = req.headers.get('authorization');`,
        `    if (!auth || !auth.startsWith('Bearer ')) return null;`,
        `    return auth.slice(7) || null;`,
        `}`,
        ``,
    ].join("\n");
}
