// Auto-generated by Codabra — do not edit manually
import { NextRequest } from 'next/server';

/**
 * Extracts the authenticated user ID from the request's Authorization header.
 * Expects a Bearer token in the format: "Authorization: Bearer <token>"
 * In production, replace this with proper JWT verification.
 * Returns null when the header is missing or malformed.
 */
export function getAuthUser(req: NextRequest): string | null {
    const auth = req.headers.get('authorization');
    if (!auth || !auth.startsWith('Bearer ')) return null;
    return auth.slice(7) || null;
}
