// Auto-generated by Codabra — do not edit manually
import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import * as schema from '@/drizzle/schema';

const sqlite = new Database('sqlite.db');
export const db = drizzle(sqlite, { schema });
